"""Write docs/progress/SLIDE_POINTS.md from the presentation deck (text and speaker notes).

  python cot-disclosure/progress/extract_slides.py
  python cot-disclosure/progress/extract_slides.py --deck path/to/deck.pptx

Default deck: presentation/progress/CSE598_Group10_progress_final.pptx. If that file is
missing, the newest committed deck (presentation/CSE598_Group10_progress_Presentation_v2.pptx)
is used and the page says so.
"""
import argparse
from pathlib import Path

from pptx import Presentation

REPO = Path(__file__).resolve().parents[2]
FINAL = REPO / "presentation" / "progress" / "CSE598_Group10_progress_final.pptx"
FALLBACK = REPO / "presentation" / "CSE598_Group10_progress_Presentation_v2.pptx"
OUT = REPO / "docs" / "progress" / "SLIDE_POINTS.md"
NOTES = [
    "Track letters on the deck follow the earlier plan (A = more models, Arsha; B = multi-agent, Shrey; "
    "C = explain and fix, Ritik). The scope update uses A = explain and fix (Ritik), B = test widely (Arsha), "
    "C = multi-agent (Shrey); see docs/plan/PROJECT_PLAN.md.",
    "The deck plans DeepSeek V4 Flash for thinking on/off; the scope update plans closed models from OpenAI, "
    "Anthropic and xAI plus Qwen3 in Ollama (docs/plan/TRACK_B_test_widely.md).",
    "The deck says 'cue' in a few places (slide 3); the docs now say 'hint'.",
]


def shape_text(shape):
    lines = []
    if shape.has_text_frame:
        lines += [p.text.strip() for p in shape.text_frame.paragraphs if p.text.strip()]
    if getattr(shape, "has_table", False) and shape.has_table:
        rows = [[c.text.strip().replace("\n", " ") for c in r.cells] for r in shape.table.rows]
        lines += ["| " + " | ".join(rows[0]) + " |", "|" + "---|" * len(rows[0])] + ["| " + " | ".join(r) + " |" for r in rows[1:]]
    if shape.shape_type == 6:  # group
        for sub in shape.shapes:
            lines += shape_text(sub)
    return lines


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--deck", type=Path)
    a = ap.parse_args()
    deck = a.deck or (FINAL if FINAL.exists() else FALLBACK)
    pres = Presentation(deck)
    out = ["# Slide points (extracted from the deck)", "",
           f"Source: `{deck.relative_to(REPO)}`, every slide's text and speaker notes, generated by "
           "`cot-disclosure/progress/extract_slides.py`. Do not edit by hand; re-run the script after changing the deck.", ""]
    if deck != FINAL:
        out += [f"**Note:** `{FINAL.relative_to(REPO)}` was not found, so this page comes from "
                f"`{deck.relative_to(REPO)}`. Re-run the script once the final deck is in place.", ""]
    out += ["**Differences from the updated scope** (checked by hand when this page was generated):", ""]
    out += [f"- {n}" for n in NOTES] + [""]
    for i, slide in enumerate(pres.slides, 1):
        lines = [l for sh in slide.shapes for l in shape_text(sh)]
        title = lines[0] if lines else f"Slide {i}"
        notes = slide.notes_slide.notes_text_frame.text.strip() if slide.has_notes_slide else ""
        out += [f"## Slide {i}: {title}", "", "**On the slide:**", ""]
        out += [l if l.startswith("|") else f"- {l}" for l in lines[1:]] or ["- (no other text)"]
        out += ["", "**Speaker notes:**", "", notes or "(none)", ""]
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(REPO)} from {deck.relative_to(REPO)} ({len(pres.slides)} slides)")


if __name__ == "__main__":
    main()
